version: 2
jobs:
  build:
    docker:
      - image: spritsail/alpine-cmake:3.9

    steps:
      - run: 
          name: Install Git
          command: 'apk add git'

      - run:
          name: Install Catch2
          command: 'mkdir /Catch2 && git clone https://github.com/catchorg/Catch2.git /Catch2 && cmake /Catch2 -B/Catch2/build -H/Catch2 -DBUILD_TESTING=OFF && cmake --build /Catch2/build/ --target install'
      
      - checkout

      - run:
          name: Build
          command: 'cmake -H. -Bbuild'

      - run:
          name: Create binaries
          command: 'cmake --build build'

      - run:
          name: Run unit tests
          command: './build/rational-tests'